---
title: "Reporte"
output:
  word_document:
    toc: TRUE
    toc_depth: 2
    reference_docx: 00_plantilla-pec.docx
    
---




```{r alistamiento, include = FALSE, results = "hide", message = FALSE, warning = FALSE, fig.show = "hide"}
library(knitr)
library(readr)
library(lubridate)
library(dplyr)
library(forcats)
library(ggplot2)
library(magrittr)
library(stringr)

```
 
```{r opciones, include = FALSE, results = "hide", message = FALSE, warning = FALSE, fig.show = "hide"}
opts_chunk$set(include = FALSE, results = "hide", message = FALSE, warning = FALSE, fig.show = "hide", echo = FALSE)

```


```{r parametros}
lista_parametros <- list(
  min_company = 20,
  top_companies = 7,
  top_titles = 50,
  carpeta_datos = "datos",
  carpeta_datos_brutos = "brutos",
  carpeta_desarrollo = "desarrollo",
  archivo_datos = "Levels_Fyi_Salary_Data.csv",
  archivo_plantilla_rmd = "00_plantilla-desagregado.rmd",
  archivo_analisis_desagregado = "00_analisis_desagregado.rmd"
)

```


```{r carga}
lista_parametros %$%
  file.path(
    carpeta_datos,
    carpeta_datos_brutos,
    archivo_datos
  ) %>% 
  read_csv() -> tabla_datos_1

```


```{r top_empresas}
tabla_datos_1 %>% 
  count(company) %>% 
  top_n(lista_parametros$top_titles) %>% 
  mutate(
    company = fct_reorder(company, n, mean)
  ) -> tabla_top_empresas

```


# Análisis desagregado por compañía

En esta sección se realiza un análisis por compañía.

```{r lectura-plantilla}
lista_parametros %$%
  file.path(
    carpeta_desarrollo,
    archivo_plantilla_rmd
  ) %>% 
  read_lines() %>% 
  paste(collapse = "\n") -> texto_plantilla_rmd

```


```{r generacion-analisis}

lista_analisis_desagregado <- list()

for(nombre_empresa in tabla_top_empresas$company){
  str_replace_all(
    texto_plantilla_rmd,
    pattern = "company_name", 
    replacement = nombre_empresa
    ) -> lista_analisis_desagregado[nombre_empresa]
}

lista_analisis_desagregado %>% 
  paste(collapse = "\n") -> texto_analisis_desagregado

```


```{r escritura-analisis}
lista_parametros %$%
  file.path(
    carpeta_desarrollo,
    archivo_analisis_desagregado
  ) -> caracter_ruta_analisis_desagregado

write_lines(texto_analisis_desagregado, caracter_ruta_analisis_desagregado)

```


```{r escritura-analisis, child=lista_parametros$archivo_analisis_desagregado}
```

